### ISSUE TITLE
Adding Tags is Bugged

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1261]
Currently adding tags to MapStories/StoryLayers is bugged. Adding tags is causing them to become unpublished, and republishing it is getting rid of the tags that were just added.

It's likely just a small error with POSTing the django forms.

**Comment by garnertb** [comment]
Need regression tests included in PR for this.

**Comment by travislbrundage** [comment]
This is resolved. Adding tags does not unpublish anymore (although I'm not sure if there are regression tests in place).

**Comment by jonpmarino** [comment]
@travislbrundage if this is resolved we can close, right?

**Comment by jj0hns0n** [comment]
@travislbrundage Im still seeing this behavior. How do I somehow verify that Im on the latest and this is not just a problem with my local enviro?
