### ISSUE TITLE
Add a way to control maps/layers on org pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#768]
After doing #767 we should give admins more control over the maps and layers. Right now they are derived only from the users. So any map a user makes is associated with that organization. It'd be better to have finer grained control, for an organization to control which maps and layers they want to be associated with them. Then users would be able to make maps for multiple organizations, or also personal maps that they don't associate with the organization.

**Comment by cholmes** [comment]
Notes from @jonpmarino - 

In a dream world, the admin could perhaps have delete powers…in other words, all the storylayers/mapstories of the users assigned to the page would naturally pool into the Org page, but the admin could then remove some from viewing there if he/she so chooses. Not deleting the content, of course…just curating what appears on the Org page.

**Comment by ischneider** [comment]
Right now, the maps and layers are totally random (actually all content there is).

The org is a user so they have the ability to add both layers and maps to their 'favorites'. We could use this collection to populate the tabs in the org page. This would achieve the goal of allowing complete (but not automatic) control over what appears there.

**Comment by cholmes** [comment]
@ischneider That sounds like a very good way to go. 

Do we have a way for the organization to login though? Like for this to work wouldn't the org needed to be logged in as a user, to have the favorite functionality?

**Comment by ischneider** [comment]
As implemented, an Org is a user. This is a disadvantage though, with the current implementation as one would have to log in to manage the Org versus just being an admin. I think it makes sense though, as I'd guess most Org users would be doing that. The favorites could be exposed in the admin interface to make up for the disadvantage of an admin not being able to modify using the existing interface.

**Comment by cholmes** [comment]
I do think that having people log in as the org to manage it is fine, and indeed preferable. Everything else one can manage through the org page itself. So I'd see the workflow for new org pages being:

Admin creates a new org
Admin sets the password for the new org
Admin tells any org users the password and org user name
org users login and edit content through the org page edit links, and select favorite maps, layers and users

That seems ideal to me.

Favorites exposed through admin is less ideal, if the above isn't too hard. Seems like the only thing we'd need is the way to create a password for the org.

In time we'll get deeper permissioning, etc. But this seems like it should work for now.

**Comment by emloux** [comment]
@ischneider - Just tried to log in on dev as AnotherOrganization and weren't able to see users we had favorited or edit the organization page.

**Comment by ischneider** [comment]
@emloux sorry, some sloppyness made it in there. should be working now.

**Comment by emloux** [comment]
@ischneider Just took a look on dev and am still seeing the same issues from yesterday. Did you deploy this fix to dev?

**Comment by ischneider** [comment]
Hmm, the favorites were all working and I just added some more. There was a permissions issue on editing links but I just fixed that and verified. I don't recall the need for a hard refresh, but can your try that, too?

**Comment by cholmes** [comment]
@ischneider Emily and I were a bit confused on which page to be on. 

I got it working, and added another org successfully.

One small thing, when adding lots (like 10) layers they just extend down. I think that's fine for now, but eventually we'll probably want a scroll bar, and to do random display. But this is good for now.

Oh, and also would be good to eventually do the 'stories used by', with maps that are made from the layers favorited. But that can wait as well. Let's just push what's there to production.
