### ISSUE TITLE
adding a layer with no time info when map contains a time aware layer raises error

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#90]
Start up the map composer, add the conflicts layer and then add the New Orleans school layer.

You'll get:

range is not defined
http://localhost:8081/script/@TimeManager.js/OpenLayers/Control/TimeManager.js
Line 301

**Comment by mpriour** [comment]
fixed in commit
https://github.com/mpriour/TimeManager_OpenLayers-Addin/commit/8b4b70246860481284eb13418544f0f070dac858

On Wed, Dec 14, 2011 at 2:45 AM, Bart van den Eijnden <
reply@reply.github.com

> wrote:
> 
> Start up the map composer, add the conflicts layer and then add the New
> Orleans school layer.
> 
> You'll get:
> 
> range is not defined
> 
> http://localhost:8081/script/@TimeManager.js/OpenLayers/Control/TimeManager.js
> Line 301
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/90

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by bartvde** [comment]
Even though I have pulled in the latest TimeManager, I am still getting an error:

range is not defined
http://localhost:8081/script/@TimeManager.js/OpenLayers/Control/TimeManager.js
Line 305

**Comment by bartvde** [comment]
I can confirm this is working fine now. Closing.
